image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y flex bison make gcc
      make
    command: |
      ./build/ierc --interactive examples/missing_semi.lang || true
